#!/bin/bash

QUARTUS_VER=21.1
NIOS_DIR=/home/$( ls /home/ | awk '{print $1}' )/intelFPGA_lite/$QUARTUS_VER/nios2eds/


echo
echo "WARNING: only works with:"
echo " - Quartus Lite version $QUARTUS_VER"
echo " - Nios install in $NIOS_DIR"
echo
echo
echo "NOTE: If you install in another location or use another version, open this file and edit to the correct info "
echo

if [ 'root' != $( whoami ) ] ; then
	echo "Please run as root! (sudo ${0})"
	exit 1;
fi

# root is super needed for the compilation to complete
$NIOS_DIR/nios2_command_shell.sh