#!/bin/bash

set -eu -o pipefail # fail on error , debug all lines

echo
echo "NOTE: Must evoke Nios2 shell before continue"
echo "Executing..."
echo

if [ 'root' != $( whoami ) ] ; then
	echo "Please run as root! (sudo ${0})"
exit 1;
fi

# Origin
# Copyright (C) 2021 Intel Corporation 
# Licensed under the MIT license. See LICENSE file in the project root for
# full license information

# Summary of compile&build commands 

# Generate Qsys RTL files and .sopcinfo file
qsys-generate -syn qsys_top.qsys

# Build NiosII software and mem_init hex file
if [ -f "./nios2/RFS_SENSOR_bsp/*.mk" ] ; then
	rm -rf ./nios2/RFS_SENSOR_bsp/*.mk
fi

if [ -f "./nios2/RFS_SENSOR_bsp/*.bsp" ] ; then
	rm -rf ./nios2/RFS_SENSOR_bsp/*.bsp
fi
# rm nios2/RFS_SENSOR_bsp/*.mk nios2/RFS_SENSOR_bsp/*.bsp

cd nios2/RFS_SENSOR
if [ -f Makefile ]; then
  rm Makefile
fi
./create-this-app
make mem_init_generate
  
cd ../..

echo
echo "Remember to exit nios shell before execute Step 2 - compile the FPGA design"
echo
