#!/bin/bash

set -eu -o pipefail # fail on error , debug all lines

if [ 'root' != $( whoami ) ] ; then
	echo "Please run as root! (sudo ${0})"
exit 1;
fi

# Origin
# Copyright (C) 2021 Intel Corporation 
# Licensed under the MIT license. See LICENSE file in the project root for
# full license information

echo
echo "Remember to run Step 1 first (s1_build_qsys_nios)"
echo "If return error, open Quartus and compile in the old fashion way"
echo "Then open this file for the RBF file generation"
echo

# Compile FPGA design
quartus_sh --flow compile ap064


# Generate RBF file
cd output_files
quartus_cpf -c -o bitstream_compression=on ap064.sof ap064.rbf


cd ..
