#!/bin/bash
#enable buildx environment for building the container of De10-nano application with Azure.
# ref Step 2: https://www.intel.com/content/www/us/en/developer/articles/technical/reconfigure-an-fpga-from-the-cloud-with-containers.html

set -eu -o pipefail #fail on error, debug all lines

/home/andreww/intelFPGA_lite/21.1/embedded/embedded_command_shell.sh
